### ISSUE TITLE
Creation of JSON specifications to define the HTML Structure for generation of all the entities defined in LDS

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/lab-data-service-dashboard#18]
Creation of JSON specifications to define the HTML Structure for generation of all the entities defined in LDS. CRUD operations for all these entities need to be defined in JSON Specifications.

**Comment by obliviateandsurrender** [comment]
@madhavipuliraju there seem to be a little problem with your JSON format, since var keyword is not defined in JSON, hence the data would not be parsed. However the format in which you mailed me the json file seemed to work totally. Can you please look into it?
 [JSON](https://github.com/vlead/lab-data-service-dashboard/blob/web-app/src/runtime/rest/web-frontend.org#add-asset)

**Comment by madhavipuliraju** [comment]
@obliviateandsurrender JSON Specifications for all Add operations of all entities are completed and Tested as well. JSON specifications for GET, UPDATE and  DELETE operations are in Progress and not tested yet. Please let me know if there is still problem with JSON formats for ADD operations.

**Comment by madhavipuliraju** [comment]
Please refer to: https://github.com/vlead/lab-data-service-dashboard/blob/web-app/src/runtime/rest/web-frontend.org#json
