### ISSUE TITLE
Unit Test cases failed to run without database creation manually

### ISSUE THREAD

**Issue by ksripathi** [vlead/lab-data-service-dashboard#24]
Ideally all the unit test cases should run in their separate test environments.

For running unit test cases which requires database setup.
Setup and teardown methods should be used and database and tables creation has to be happen on the fly.

But I observed that to test add_user functionality it expects database and tables to be populated manually

`sqlalchemy.exc.ProgrammingError: (oursql.ProgrammingError) (1049, "Unknown database 'ldsdashboard'", None)`

This is to be resolved

**Comment by ksripathi** [comment]
For running unit test cases `sqlite` db has to be used various in production deployment `mysql` has to be used application should be configured to support both test & production environments

**Comment by obliviateandsurrender** [comment]
I tried to fix the test cases by changing the uri to `sqlite:///`. Lemme know if it fixes the issue, if not then suggest me some other way to achieve the required `sqlite db`.
Changes are done in latest commit and since the college has started it would be difficult for me to update frequently but I'll do it as soon it is possible. :) 
Adding it as a bug until fixed for now.
